@echo off
echo Starting Backend...
start "Backend" cmd /k "call .venv\Scripts\activate.bat && cd backend && docker compose up -d postgres redis chromadb && fastapi dev app/main.py"
echo Starting Frontend in Docker...
start "Frontend" cmd /k "cd frontend && docker compose up -d --build"
